[package]
name = "core"
version = "0.1.0"
edition = "2024"

[lib]
name = "core"
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.2.4", default-features = false, features = ["async"] }
napi-derive = "3.2.4"
hyper = { version = "1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
once_cell = "1.21.3"
dashmap = "6.1.0"
urlencoding = "2.1.3"
httpdate = "1.0.3"
parking_lot = "0.12.5"
serde = { version = "1.0.228", features = ["derive"] }
regex = "1.12.2"
serde_json = "1.0.145"
matchit = "0.9.0"
ahash = "0.8.12"
base64 = "0.22.1"
socket2 = "0.6.1"
futures-util = "0.3.31"

[dev-dependencies]
tokio-test = "0.4.4"

[build-dependencies]
napi-build = "2.2.3"
