[package]
name = "kito" # cli
version = "0.1.0"
edition = "2024"
authors = ["NehuÃ©n <github.com/nehu3n>"]
description = "ğŸ„ Kito's official CLI."
license = "MIT"
repository = "https://github.com/kitojs/kito"
readme = "readme.md"
include = [
    "src/*",
    "Cargo.toml",
    "readme.md",
]

[[bin]]
name = "kito"
path = "src/main.rs"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]